apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edw-jenkins
  name: edw-jenkins
  namespace: edw-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edw-jenkins
  template:
    metadata:
      labels:
        app: edw-jenkins
        wildcardcertmanager: aware
        internalcert: wildcard
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::248273529068:role/test-snf-asg-role
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      # serviceAccountName: edw-jenkins
      initContainers:
        - name: install-helm
          image: jenkins/jenkins:lts
          command: ["sh", "-c"]
          securityContext:
            runAsUser: 0
          args: [
              "apt-get update && \
              apt-get install -y curl && \
              apt install python3 && \
              apt-get clean
              | curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
              chmod +x get_helm.sh && \
              ./get_helm.sh; cp /usr/local/bin/* /dependencies/ ;",
            ]
          volumeMounts:
            - name: helm
              mountPath: /dependencies
              # subPath: helm.bin
      containers:
        - name: edw-jenkins
          image: jenkins/jenkins:lts
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
              protocol: TCP
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: helm
              mountPath: /usr/local/bin
              # subPath: helm.bin
              readOnly: true
      volumes:
        - name: helm
          persistentVolumeClaim: 
            claimName: jenkins-pv-claim 
